// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPathResolver creates a new instance of PathResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPathResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *PathResolver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PathResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PathResolver is an autogenerated mock type for the PathResolver type
type PathResolver struct {
	mock.Mock
}

type PathResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *PathResolver) EXPECT() *PathResolver_Expecter {
	return &PathResolver_Expecter{mock: &_m.Mock}
}

// EvalSymlinks provides a mock function for the type PathResolver
func (_mock *PathResolver) EvalSymlinks(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for EvalSymlinks")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PathResolver_EvalSymlinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalSymlinks'
type PathResolver_EvalSymlinks_Call struct {
	*mock.Call
}

// EvalSymlinks is a helper method to define mock.On call
//   - s string
func (_e *PathResolver_Expecter) EvalSymlinks(s any) *PathResolver_EvalSymlinks_Call {
	return &PathResolver_EvalSymlinks_Call{Call: _e.mock.On("EvalSymlinks", s)}
}

func (_c *PathResolver_EvalSymlinks_Call) Run(run func(s string)) *PathResolver_EvalSymlinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PathResolver_EvalSymlinks_Call) Return(s1 string, err error) *PathResolver_EvalSymlinks_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *PathResolver_EvalSymlinks_Call) RunAndReturn(run func(s string) (string, error)) *PathResolver_EvalSymlinks_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function for the type PathResolver
func (_mock *PathResolver) FileExists(s string) bool {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// PathResolver_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type PathResolver_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - s string
func (_e *PathResolver_Expecter) FileExists(s any) *PathResolver_FileExists_Call {
	return &PathResolver_FileExists_Call{Call: _e.mock.On("FileExists", s)}
}

func (_c *PathResolver_FileExists_Call) Run(run func(s string)) *PathResolver_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PathResolver_FileExists_Call) Return(b bool) *PathResolver_FileExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *PathResolver_FileExists_Call) RunAndReturn(run func(s string) bool) *PathResolver_FileExists_Call {
	_c.Call.Return(run)
	return _c
}
