// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/scality/raidmgmt/pkg/implementation/raidcontroller/megaraid"
	mock "github.com/stretchr/testify/mock"
)

// NewRunner creates a new instance of Runner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Runner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

type Runner_Expecter struct {
	mock *mock.Mock
}

func (_m *Runner) EXPECT() *Runner_Expecter {
	return &Runner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type Runner
func (_mock *Runner) Run(args []string) (*megaraid.CmdOutput, error) {
	ret := _mock.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *megaraid.CmdOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (*megaraid.CmdOutput, error)); ok {
		return returnFunc(args)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) *megaraid.CmdOutput); ok {
		r0 = returnFunc(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*megaraid.CmdOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Runner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - args []string
func (_e *Runner_Expecter) Run(args any) *Runner_Run_Call {
	return &Runner_Run_Call{Call: _e.mock.On("Run", args)}
}

func (_c *Runner_Run_Call) Run(run func(args []string)) *Runner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_Run_Call) Return(cmdOutput *megaraid.CmdOutput, err error) *Runner_Run_Call {
	_c.Call.Return(cmdOutput, err)
	return _c
}

func (_c *Runner_Run_Call) RunAndReturn(run func(args []string) (*megaraid.CmdOutput, error)) *Runner_Run_Call {
	_c.Call.Return(run)
	return _c
}
