// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	megaraid "github.com/scality/raidmgmt/megaraid"
	mock "github.com/stretchr/testify/mock"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Run provides a mock function with given fields: args
func (_m *Runner) Run(args []string) (*megaraid.CmdOutput, error) {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *megaraid.CmdOutput
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (*megaraid.CmdOutput, error)); ok {
		return rf(args)
	}
	if rf, ok := ret.Get(0).(func([]string) *megaraid.CmdOutput); ok {
		r0 = rf(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*megaraid.CmdOutput)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRunner creates a new instance of Runner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runner {
	mock := &Runner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
