name: Promote
run-name: "Promote ${{ github.ref_name }}"

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    uses: scality/workflows/.github/workflows/promote.yaml@7d91dc4ebbe136b54518aa42a1ad6014f8f91526 # v2.9.1
    permissions:
      contents: write
